# Generated by Django 4.2.29 on 2026-04-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='archivo',
            field=models.CharField(help_text='URL de Cloudinary o ruta', max_length=500),
        ),
    ]
