# Generated by Django 4.2.29 on 2026-04-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_alter_multimedia_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('mantenimiento', 'En Mantenimiento'), ('reservado', 'Reservado'), ('oculto', 'Oculto')], default='disponible', max_length=20),
        ),
    ]
