# Generated by Django 4.2.29 on 2026-04-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_alter_inmueble_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='longitud',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='gps',
            field=models.CharField(blank=True, help_text='Coordenadas GPS (ej. -17.7898, -63.1939)', max_length=100, null=True),
        ),
    ]
