# Generated by Django 4.2.29 on 2026-05-03 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_options_remove_usuario_username_and_more'),
        ('inmuebles', '0004_alter_inmueble_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_chat', to='usuarios.chat'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='clausulas',
            field=models.TextField(blank=True, help_text='Cláusulas adicionales del contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='condiciones_uso',
            field=models.TextField(blank=True, help_text='Condiciones de uso del inmueble'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='dia_pago',
            field=models.PositiveIntegerField(default=1, help_text='Día del mes para pago (1-28)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma_pago',
            field=models.CharField(blank=True, default='Stripe / Transferencia', max_length=100),
        ),
        migrations.AddField(
            model_name='contrato',
            name='incluye_servicios',
            field=models.TextField(blank=True, help_text='Servicios incluidos (agua, luz, internet, etc.)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='moneda',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='contrato',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo si el cliente rechaza'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='penalidades',
            field=models.TextField(blank=True, help_text='Penalidades por incumplimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='politica_cancelacion',
            field=models.TextField(blank=True, help_text='Política de cancelación anticipada'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='restricciones',
            field=models.TextField(blank=True, help_text='Restricciones (mascotas, subarriendo, etc.)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado al cliente'), ('aceptado', 'Aceptado por el cliente'), ('rechazado', 'Rechazado por el cliente'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('pendiente', 'Pendiente')], default='borrador', max_length=20),
        ),
    ]
