# Generated by Django 4.2.30 on 2026-04-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_remove_inmueble_latitud_remove_inmueble_longitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('zona', models.CharField(blank=True, max_length=100)),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('referencia', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='banos',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('mantenimiento', 'En Mantenimiento'), ('reservado', 'Reservado'), ('oculto', 'Oculto')], db_index=True, default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='habitaciones',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='superficie',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Superficie en metros cuadrados', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='direccion_fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmueble', to='inmuebles.direccion'),
        ),
    ]
