# Generated by Django 4.2.30 on 2026-05-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_configuracionsistema'),
        ('inmuebles', '0005_contrato_actualizado_contrato_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='pago',
            field=models.ForeignKey(blank=True, help_text='Pago transaccional del cual se generó la comisión', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='pagos.pago'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='pagada',
            field=models.BooleanField(default=True, help_text='Las comisiones transaccionales se asumen descontadas/pagadas al instante'),
        ),
    ]
