# Generated by Django 4.2.30 on 2026-04-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_direccion_alter_inmueble_banos_alter_inmueble_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='zona',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
