# Generated by Django 4.2.29 on 2026-05-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_cita_horariodisponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='antecedentes',
            field=models.TextField(blank=True, help_text='Contexto previo, situación legal y antecedentes del inmueble'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='clausulas_especiales',
            field=models.TextField(blank=True, help_text='Cláusulas especiales adicionales pactadas entre las partes'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='uso_exclusivo',
            field=models.TextField(blank=True, help_text='Uso permitido del inmueble (vivienda, comercial, mixto, etc.)'),
        ),
    ]
