# Generated by Django 4.2.30 on 2026-05-15 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_cita_horariodisponible'),
        ('inmuebles', '0006_comision_pago_alter_comision_pagada'),
    ]

    operations = [
    ]
