# Generated by Django 4.2.29 on 2026-05-21 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmuebles', '0007_contrato_antecedentes_contrato_clausulas_especiales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_titulo', models.CharField(help_text='URL de Cloudinary del documento subido', max_length=500)),
                ('texto_ocr', models.TextField(blank=True, help_text='Texto extraído del documento')),
                ('resultado_ia', models.JSONField(blank=True, help_text='Resultado del análisis legal de Groq en formato JSON', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('verificado', 'Verificado'), ('observado', 'Con Observaciones'), ('rechazado', 'No Válido'), ('error', 'Error de Procesamiento')], default='pendiente', max_length=20)),
                ('score_confianza', models.PositiveIntegerField(blank=True, help_text='Puntaje de confianza de 0 a 100', null=True)),
                ('resumen_publico', models.TextField(blank=True, help_text='Resumen corto visible al público')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('inmueble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verificacion_titulo', to='inmuebles.inmueble')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación de Título',
                'verbose_name_plural': 'Verificaciones de Títulos',
                'db_table': 'inmuebles_verificacion_titulo',
                'ordering': ['-creado'],
            },
        ),
    ]
