# Generated by Django 4.2.30 on 2026-05-21 03:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0007_merge_20260514_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='precio',
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_oferta', models.CharField(choices=[('alquiler', 'Alquiler'), ('venta', 'Venta'), ('anticretico', 'Anticrético')], db_index=True, default='alquiler', max_length=20)),
                ('precio', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], db_index=True, default='borrador', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='inmuebles.inmueble')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'db_table': 'inmuebles_publicacion',
                'ordering': ['-creado'],
            },
        ),
    ]
