# Generated by Django 4.2.30 on 2026-04-14 00:11

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0008_alter_inmueble_precio'),
    ]

    operations = [
        UnaccentExtension(),
    ]
