# Generated by Django 4.2.30 on 2026-05-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0008_remove_inmueble_precio_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='valor_activo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor catastral o de referencia del activo físico (DDRR). Interno, no se publica.', max_digits=14, null=True),
        ),
    ]
