# Generated by Django 4.2.29 on 2026-05-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0007_merge_20260514_2136'),
        ('inmuebles', '0008_verificaciontitulo'),
    ]

    operations = [
    ]
