# Generated by Django 4.2.30 on 2026-05-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0009_add_valor_activo_to_inmueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('panorama360', 'Panorama 360°')], default='imagen', max_length=20),
        ),
    ]
