# Generated by Django 4.2.30 on 2026-05-22 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0010_add_panorama360_tipo_multimedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.FloatField(help_text='Ángulo vertical (-90 a 90 grados)')),
                ('yaw', models.FloatField(help_text='Ángulo horizontal (-180 a 180 grados)')),
                ('texto_ayuda', models.CharField(blank=True, help_text="Texto informativo que aparece al pasar el cursor (tooltip), ej: 'Ir a Cocina'", max_length=100)),
                ('escena_destino', models.ForeignKey(help_text='Panorama destino al cual viajará el visor al hacer clic', on_delete=django.db.models.deletion.CASCADE, related_name='hotspots_entrada', to='inmuebles.multimedia')),
                ('escena_origen', models.ForeignKey(help_text='Panorama de origen donde se dibuja el hotspot (debe ser tipo panorama360)', on_delete=django.db.models.deletion.CASCADE, related_name='hotspots_salida', to='inmuebles.multimedia')),
                ('inmueble', models.ForeignKey(help_text='Inmueble al que pertenece el recorrido', on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='inmuebles.inmueble')),
            ],
            options={
                'verbose_name': 'Punto de Transición (Hotspot)',
                'verbose_name_plural': 'Puntos de Transición (Hotspots)',
                'db_table': 'inmuebles_hotspot',
            },
        ),
    ]
