# Generated by Django 4.2.30 on 2026-05-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0011_hotspot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multimedia',
            options={'ordering': ['orden', '-principal', '-subido'], 'verbose_name': 'Multimedia', 'verbose_name_plural': 'Multimedia'},
        ),
        migrations.AddField(
            model_name='multimedia',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización'),
        ),
    ]
