# Generated by Django 4.2.30 on 2026-05-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0012_alter_multimedia_options_multimedia_orden'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotspot',
            unique_together={('escena_origen', 'escena_destino')},
        ),
    ]
