# Generated by Django 4.2.30 on 2026-05-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0009_merge_20260521_1704'),
        ('inmuebles', '0013_alter_hotspot_unique_together'),
    ]

    operations = [
    ]
