# Generated by Django 4.2.30 on 2026-05-28 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0007_alter_mensaje_tipo'),
        ('inmuebles', '0014_merge_20260528_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoRecorrido360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesos_360', to='usuarios.chat')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_360_recibidos', to=settings.AUTH_USER_MODEL)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_360', to='inmuebles.inmueble')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_360_otorgados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a Recorrido 360°',
                'verbose_name_plural': 'Accesos a Recorridos 360°',
                'db_table': 'inmuebles_acceso_recorrido_360',
                'ordering': ['-creado'],
            },
        ),
    ]
