# Generated by Django 4.2.30 on 2026-05-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0015_accesorecorrido360'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorecorrido360',
            name='ultimo_acceso_visor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesorecorrido360',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
