# Generated by Django 4.2.29 on 2026-06-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0016_accesorecorrido360_ultimo_acceso_visor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha', '-hora_inicio'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AddField(
            model_name='inmueble',
            name='modelo_3d',
            field=models.CharField(blank=True, help_text='URL del modelo 3D (.glb) para visualización AR', max_length=500, null=True),
        ),
    ]
