# Generated by Django 4.2.29 on 2026-06-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inmuebles", "0017_alter_cita_options_inmueble_modelo_3d"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multimedia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("imagen", "Imagen"),
                    ("video", "Video"),
                    ("panorama360", "Panorama 360°"),
                    ("musica", "Música"),
                ],
                default="imagen",
                max_length=20,
            ),
        ),
    ]
