# Generated by Django 4.2.30 on 2026-04-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_chat_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Cédula de Identidad'),
        ),
    ]
