# Generated by Django 4.2.30 on 2026-05-21 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0008_remove_inmueble_precio_publicacion'),
        ('usuarios', '0005_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='inmuebles.publicacion'),
        ),
    ]
