# Generated by Django 4.2.30 on 2026-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_chat_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('video', 'Video'), ('ubicacion', 'Ubicación'), ('emoji', 'Emoji'), ('whatsapp', 'WhatsApp'), ('recorrido360', 'Recorrido 360°')], default='texto', max_length=20),
        ),
    ]
