# Generated by Django 4.2.29 on 2026-06-14 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_mensaje_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-id']},
        ),
    ]
