# Generated by Django 5.2.8 on 2026-04-17 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmuebles', '0002_initial'),
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpago',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_pagos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inmuebles.contrato'),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pagos.pago'),
        ),
        migrations.AddField(
            model_name='detallepago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pagos.pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pagos.tipopago'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tipo_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes', to='pagos.tipoplan'),
        ),
    ]
