# Generated by Django 4.2.29 on 2026-05-03 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmuebles', '0004_alter_inmueble_precio'),
        ('usuarios', '0003_alter_usuario_options_remove_usuario_username_and_more'),
        ('pagos', '0003_tablas_espanol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('compra', 'Compra'), ('alquiler', 'Alquiler'), ('deposito', 'Depósito'), ('mensualidad', 'Mensualidad')], default='mensualidad', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='usd', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('stripe_session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=20)),
                ('comprobante_url', models.URLField(blank=True, help_text='URL del recibo de Stripe')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='usuarios.chat')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_stripe', to='inmuebles.contrato')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_pagadas', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción Stripe',
                'verbose_name_plural': 'Transacciones Stripe',
                'db_table': 'pagos_transaccion_stripe',
                'ordering': ['-creado'],
            },
        ),
    ]
