# Generated by Django 4.2.30 on 2026-05-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_transaccionstripe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_comision_plataforma', models.DecimalField(decimal_places=2, default=5.0, help_text='Porcentaje de comisión por transacción (ej. 5.00 para 5%)', max_digits=5)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'pagos_configuracion_sistema',
            },
        ),
    ]
